-- V11: Campos empresariales de catalogo, inventario y Kardex.

ALTER TABLE productos ADD COLUMN IF NOT EXISTS sku VARCHAR(50);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS codigo_barras VARCHAR(80);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS costo DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS margen_porcentaje DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS imagen_url VARCHAR(500);
ALTER TABLE productos ADD COLUMN IF NOT EXISTS unidad_venta VARCHAR(30) NOT NULL DEFAULT 'unidad';
ALTER TABLE productos ADD COLUMN IF NOT EXISTS fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE productos
SET sku = 'CAF-PROD-' || id
WHERE sku IS NULL OR TRIM(sku) = '';

UPDATE productos
SET codigo_barras = '775000' || LPAD(CAST(id AS VARCHAR), 6, '0')
WHERE codigo_barras IS NULL OR TRIM(codigo_barras) = '';

ALTER TABLE productos ALTER COLUMN sku SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_productos_sku ON productos (sku);
CREATE UNIQUE INDEX IF NOT EXISTS ux_productos_codigo_barras ON productos (codigo_barras);
CREATE INDEX IF NOT EXISTS idx_productos_nombre ON productos (nombre);

ALTER TABLE inventario ADD COLUMN IF NOT EXISTS codigo_insumo VARCHAR(50);
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS categoria VARCHAR(80) NOT NULL DEFAULT 'General';
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(120) NOT NULL DEFAULT 'Almacen principal';
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS lote VARCHAR(80);
ALTER TABLE inventario ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE;

UPDATE inventario
SET codigo_insumo = 'CAF-INS-' || id
WHERE codigo_insumo IS NULL OR TRIM(codigo_insumo) = '';

ALTER TABLE inventario ALTER COLUMN codigo_insumo SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_inventario_codigo_insumo ON inventario (codigo_insumo);
CREATE INDEX IF NOT EXISTS idx_inventario_categoria ON inventario (categoria);
CREATE INDEX IF NOT EXISTS idx_inventario_ubicacion ON inventario (ubicacion);

CREATE TABLE IF NOT EXISTS movimientos_inventario (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventario_id       INTEGER NOT NULL,
    tipo                VARCHAR(20) NOT NULL,
    cantidad            INTEGER NOT NULL,
    stock_anterior      INTEGER NOT NULL,
    stock_nuevo         INTEGER NOT NULL,
    costo_unitario      NUMERIC(10, 2),
    motivo              VARCHAR(250),
    referencia          VARCHAR(120),
    usuario_id          INTEGER,
    fecha_movimiento    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movimientos_inventario_item
        FOREIGN KEY (inventario_id) REFERENCES inventario (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_movimientos_inventario_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT ck_movimientos_inventario_tipo
        CHECK (tipo IN ('entrada', 'salida', 'ajuste', 'merma')),
    CONSTRAINT ck_movimientos_inventario_cantidad
        CHECK (cantidad >= 0),
    CONSTRAINT ck_movimientos_inventario_stock
        CHECK (stock_anterior >= 0 AND stock_nuevo >= 0)
);

CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_item ON movimientos_inventario (inventario_id);
CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_fecha ON movimientos_inventario (fecha_movimiento);
CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_tipo ON movimientos_inventario (tipo);

INSERT INTO movimientos_inventario (
    inventario_id,
    tipo,
    cantidad,
    stock_anterior,
    stock_nuevo,
    costo_unitario,
    motivo,
    referencia,
    fecha_movimiento
)
SELECT
    id,
    'entrada',
    cantidad,
    0,
    cantidad,
    precio_unitario,
    'Stock inicial migrado',
    'MIGRACION-V11',
    COALESCE(fecha_actualizacion, CURRENT_TIMESTAMP)
FROM inventario
WHERE NOT EXISTS (
    SELECT 1
    FROM movimientos_inventario mi
    WHERE mi.inventario_id = inventario.id
);

CREATE TABLE IF NOT EXISTS producto_receta (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id         INTEGER NOT NULL,
    inventario_id       INTEGER NOT NULL,
    cantidad_insumo     NUMERIC(10, 3) NOT NULL,
    unidad              VARCHAR(30) NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_producto_receta_producto
        FOREIGN KEY (producto_id) REFERENCES productos (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_producto_receta_inventario
        FOREIGN KEY (inventario_id) REFERENCES inventario (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_producto_receta_cantidad
        CHECK (cantidad_insumo > 0),
    CONSTRAINT ux_producto_receta_linea
        UNIQUE (producto_id, inventario_id)
);

CREATE INDEX IF NOT EXISTS idx_producto_receta_producto ON producto_receta (producto_id);
CREATE INDEX IF NOT EXISTS idx_producto_receta_inventario ON producto_receta (inventario_id);

CREATE TABLE IF NOT EXISTS lotes_inventario (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventario_id       INTEGER NOT NULL,
    codigo_lote         VARCHAR(80) NOT NULL,
    cantidad            INTEGER NOT NULL DEFAULT 0,
    fecha_vencimiento   DATE,
    fecha_ingreso       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    costo_unitario      NUMERIC(10, 2),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_lotes_inventario_item
        FOREIGN KEY (inventario_id) REFERENCES inventario (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT ck_lotes_inventario_cantidad
        CHECK (cantidad >= 0),
    CONSTRAINT ux_lotes_inventario_codigo
        UNIQUE (inventario_id, codigo_lote)
);

CREATE INDEX IF NOT EXISTS idx_lotes_inventario_item ON lotes_inventario (inventario_id);
CREATE INDEX IF NOT EXISTS idx_lotes_inventario_vencimiento ON lotes_inventario (fecha_vencimiento);

COMMENT ON TABLE movimientos_inventario IS 'Kardex de entradas, salidas, ajustes y mermas de inventario';
COMMENT ON TABLE producto_receta IS 'Relacion entre productos vendibles e insumos consumidos';
COMMENT ON TABLE lotes_inventario IS 'Control opcional de lotes y vencimientos por insumo';
