-- V12: Catalogo ampliado, categorias formales, dos almacenes y Kardex reforzado.

CREATE TABLE IF NOT EXISTS categorias_producto (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(80) NOT NULL UNIQUE,
    descripcion VARCHAR(250),
    activo      BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO categorias_producto (nombre, descripcion, activo)
SELECT v.nombre, v.descripcion, TRUE
FROM (
    VALUES
        ('Bebidas calientes', 'Cafe, chocolate e infusiones preparadas en barra'),
        ('Bebidas frias', 'Bebidas heladas, frappes, jugos y refrescos'),
        ('Postres', 'Dulces, tortas y porciones de pasteleria'),
        ('Sandwiches', 'Sandwiches, wraps y paninis preparados'),
        ('Panaderia', 'Panes, croissants, empanadas y horneados'),
        ('Desayunos', 'Platos de desayuno y combinaciones de manana'),
        ('Ensaladas', 'Opciones frescas y bowls salados'),
        ('Snacks', 'Acompanamientos rapidos y productos ligeros'),
        ('Combos', 'Promociones y combinaciones del local'),
        ('Insumos retail', 'Productos empaquetados para venta directa')
) AS v(nombre, descripcion)
WHERE NOT EXISTS (
    SELECT 1 FROM categorias_producto c WHERE c.nombre = v.nombre
);

ALTER TABLE productos ADD COLUMN IF NOT EXISTS categoria_id INTEGER;

UPDATE productos
SET categoria = 'Bebidas calientes'
WHERE LOWER(categoria) = 'bebidas';

UPDATE productos
SET categoria = 'Postres'
WHERE LOWER(categoria) = 'postres';

UPDATE productos
SET categoria = 'Sandwiches'
WHERE LOWER(categoria) IN ('comidas', 'comida');

UPDATE productos p
SET categoria_id = (
    SELECT c.id
    FROM categorias_producto c
    WHERE LOWER(c.nombre) = LOWER(p.categoria)
)
WHERE categoria_id IS NULL
  AND EXISTS (
      SELECT 1
      FROM categorias_producto c
      WHERE LOWER(c.nombre) = LOWER(p.categoria)
  );

CREATE INDEX IF NOT EXISTS idx_productos_categoria_id ON productos (categoria_id);

ALTER TABLE productos DROP CONSTRAINT IF EXISTS fk_productos_categoria;

ALTER TABLE productos
    ADD CONSTRAINT fk_productos_categoria
    FOREIGN KEY (categoria_id) REFERENCES categorias_producto (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS almacenes (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(30) NOT NULL UNIQUE,
    nombre      VARCHAR(120) NOT NULL,
    descripcion VARCHAR(250),
    activo      BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO almacenes (id, codigo, nombre, descripcion, activo)
SELECT 1, 'ALM-CENTRAL', 'Almacen Central', 'Deposito principal para insumos secos, empaques y reserva', TRUE
WHERE NOT EXISTS (SELECT 1 FROM almacenes WHERE codigo = 'ALM-CENTRAL');

INSERT INTO almacenes (id, codigo, nombre, descripcion, activo)
SELECT 2, 'ALM-BARRA', 'Almacen Barra y Produccion', 'Stock operativo para barra, cocina fria y preparacion diaria', TRUE
WHERE NOT EXISTS (SELECT 1 FROM almacenes WHERE codigo = 'ALM-BARRA');

ALTER TABLE inventario ADD COLUMN IF NOT EXISTS almacen_id INTEGER DEFAULT 1;

UPDATE inventario
SET almacen_id = 1,
    ubicacion = 'Almacen Central'
WHERE almacen_id IS NULL OR ubicacion = 'Almacen principal';

UPDATE inventario
SET almacen_id = 2,
    ubicacion = 'Almacen Barra y Produccion'
WHERE LOWER(nombre_insumo) IN ('leche evaporada', 'jarabe de vainilla');

ALTER TABLE inventario ALTER COLUMN almacen_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_inventario_almacen ON inventario (almacen_id);

ALTER TABLE inventario DROP CONSTRAINT IF EXISTS fk_inventario_almacen;

ALTER TABLE inventario
    ADD CONSTRAINT fk_inventario_almacen
    FOREIGN KEY (almacen_id) REFERENCES almacenes (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

ALTER TABLE movimientos_inventario ADD COLUMN IF NOT EXISTS almacen_id INTEGER;

UPDATE movimientos_inventario mi
SET almacen_id = (
    SELECT i.almacen_id
    FROM inventario i
    WHERE i.id = mi.inventario_id
)
WHERE almacen_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_almacen ON movimientos_inventario (almacen_id);

ALTER TABLE movimientos_inventario DROP CONSTRAINT IF EXISTS fk_movimientos_inventario_almacen;

ALTER TABLE movimientos_inventario
    ADD CONSTRAINT fk_movimientos_inventario_almacen
    FOREIGN KEY (almacen_id) REFERENCES almacenes (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;

INSERT INTO productos (
    nombre,
    precio,
    categoria,
    descripcion,
    activo,
    sku,
    codigo_barras,
    costo,
    margen_porcentaje,
    unidad_venta,
    categoria_id
)
SELECT
    v.nombre,
    v.precio,
    v.categoria,
    v.descripcion,
    TRUE,
    v.sku,
    v.codigo_barras,
    v.costo,
    CAST(ROUND(CAST(((v.precio - v.costo) / v.precio) * 100 AS NUMERIC), 2) AS DOUBLE PRECISION),
    v.unidad_venta,
    c.id
FROM (
    VALUES
        ('Espresso Simple', 7.00, 'Bebidas calientes', 'Shot de espresso intenso de origen peruano', 'CAF-BHC-001', '775120000001', 2.20, 'taza'),
        ('Espresso Doble', 9.00, 'Bebidas calientes', 'Doble espresso para servicio rapido', 'CAF-BHC-002', '775120000002', 3.10, 'taza'),
        ('Macchiato', 9.50, 'Bebidas calientes', 'Espresso marcado con espuma de leche', 'CAF-BHC-003', '775120000003', 3.40, 'taza'),
        ('Americano Grande', 10.50, 'Bebidas calientes', 'Cafe americano en vaso grande', 'CAF-BHC-004', '775120000004', 3.20, 'vaso'),
        ('Cappuccino Grande', 13.00, 'Bebidas calientes', 'Cappuccino de 12 oz con espuma cremosa', 'CAF-BHC-005', '775120000005', 4.60, 'vaso'),
        ('Latte Clasico', 12.50, 'Bebidas calientes', 'Cafe latte balanceado con leche vaporizada', 'CAF-BHC-006', '775120000006', 4.30, 'vaso'),
        ('Mocha', 14.00, 'Bebidas calientes', 'Cafe con chocolate y leche vaporizada', 'CAF-BHC-007', '775120000007', 5.20, 'vaso'),
        ('Flat White', 13.50, 'Bebidas calientes', 'Doble espresso con microespuma', 'CAF-BHC-008', '775120000008', 4.70, 'taza'),
        ('Chocolate Caliente', 11.00, 'Bebidas calientes', 'Chocolate con leche y cacao bitter', 'CAF-BHC-009', '775120000009', 4.10, 'taza'),
        ('Infusion Andina', 8.00, 'Bebidas calientes', 'Infusion herbal de muña y hierbas peruanas', 'CAF-BHC-010', '775120000010', 2.10, 'taza'),
        ('Te Verde', 7.50, 'Bebidas calientes', 'Te verde servido caliente', 'CAF-BHC-011', '775120000011', 1.90, 'taza'),
        ('Caramel Macchiato', 15.00, 'Bebidas calientes', 'Latte con caramelo y espresso', 'CAF-BHC-012', '775120000012', 5.70, 'vaso'),
        ('Cold Brew', 13.00, 'Bebidas frias', 'Cafe extraido en frio por 16 horas', 'CAF-BFR-001', '775120000013', 4.20, 'vaso'),
        ('Frappe Cafe', 15.50, 'Bebidas frias', 'Cafe frappe con crema ligera', 'CAF-BFR-002', '775120000014', 6.10, 'vaso'),
        ('Frappe Mocha', 16.50, 'Bebidas frias', 'Frappe de cafe con chocolate', 'CAF-BFR-003', '775120000015', 6.70, 'vaso'),
        ('Limonada Hierbabuena', 10.00, 'Bebidas frias', 'Limonada natural con hierbabuena', 'CAF-BFR-004', '775120000016', 3.20, 'vaso'),
        ('Jugo Naranja', 11.00, 'Bebidas frias', 'Jugo natural de naranja', 'CAF-BFR-005', '775120000017', 4.00, 'vaso'),
        ('Iced Latte', 13.50, 'Bebidas frias', 'Latte frio con hielo', 'CAF-BFR-006', '775120000018', 4.90, 'vaso'),
        ('Smoothie Fresa', 14.50, 'Bebidas frias', 'Smoothie de fresa y yogurt', 'CAF-BFR-007', '775120000019', 5.90, 'vaso'),
        ('Agua Mineral', 4.50, 'Bebidas frias', 'Botella de agua mineral sin gas', 'CAF-BFR-008', '775120000020', 1.80, 'botella'),
        ('Cheesecake Maracuya', 15.00, 'Postres', 'Porcion de cheesecake con salsa de maracuya', 'CAF-POS-001', '775120000021', 6.20, 'porcion'),
        ('Pie de Limon', 12.50, 'Postres', 'Pie de limon individual', 'CAF-POS-002', '775120000022', 4.80, 'porcion'),
        ('Tiramisu Cafetero', 16.00, 'Postres', 'Tiramisu con cafe espresso', 'CAF-POS-003', '775120000023', 6.90, 'porcion'),
        ('Muffin Arandanos', 9.50, 'Postres', 'Muffin artesanal con arandanos', 'CAF-POS-004', '775120000024', 3.50, 'unidad'),
        ('Galleta Chocochips', 6.50, 'Postres', 'Galleta grande con chips de chocolate', 'CAF-POS-005', '775120000025', 2.10, 'unidad'),
        ('Tres Leches', 13.00, 'Postres', 'Porcion de torta tres leches', 'CAF-POS-006', '775120000026', 5.20, 'porcion'),
        ('Pionono', 8.00, 'Postres', 'Pionono relleno de manjar', 'CAF-POS-007', '775120000027', 2.90, 'unidad'),
        ('Alfajor', 5.50, 'Postres', 'Alfajor con manjar blanco', 'CAF-POS-008', '775120000028', 1.80, 'unidad'),
        ('Donut Glaseada', 7.50, 'Postres', 'Donut con glaseado clasico', 'CAF-POS-009', '775120000029', 2.60, 'unidad'),
        ('Panqueque Miel', 12.00, 'Postres', 'Panqueques con miel y fruta', 'CAF-POS-010', '775120000030', 4.90, 'plato'),
        ('Sandwich Pavo', 17.50, 'Sandwiches', 'Sandwich de pavo con queso y verduras', 'CAF-SAN-001', '775120000031', 7.30, 'unidad'),
        ('Sandwich Caprese', 16.50, 'Sandwiches', 'Tomate, queso y pesto en pan artesanal', 'CAF-SAN-002', '775120000032', 6.80, 'unidad'),
        ('Panini Pollo', 18.00, 'Sandwiches', 'Panini de pollo con queso fundido', 'CAF-SAN-003', '775120000033', 7.60, 'unidad'),
        ('Croissant Mixto', 15.50, 'Sandwiches', 'Croissant con jamon y queso', 'CAF-SAN-004', '775120000034', 6.50, 'unidad'),
        ('Wrap Pollo', 17.00, 'Sandwiches', 'Wrap de pollo, verduras y salsa ligera', 'CAF-SAN-005', '775120000035', 7.00, 'unidad'),
        ('Sandwich Atun', 16.00, 'Sandwiches', 'Sandwich de atun con vegetales', 'CAF-SAN-006', '775120000036', 6.20, 'unidad'),
        ('Hamburguesa Cafe', 20.00, 'Sandwiches', 'Hamburguesa de la casa con papas', 'CAF-SAN-007', '775120000037', 9.40, 'unidad'),
        ('Club Sandwich', 22.00, 'Sandwiches', 'Triple sandwich con pollo, tocino y huevo', 'CAF-SAN-008', '775120000038', 10.20, 'unidad'),
        ('Croissant Mantequilla', 8.00, 'Panaderia', 'Croissant clasico horneado diario', 'CAF-PAN-001', '775120000039', 3.10, 'unidad'),
        ('Empanada Carne', 9.00, 'Panaderia', 'Empanada horneada rellena de carne', 'CAF-PAN-002', '775120000040', 3.80, 'unidad'),
        ('Empanada Pollo', 8.50, 'Panaderia', 'Empanada horneada rellena de pollo', 'CAF-PAN-003', '775120000041', 3.60, 'unidad'),
        ('Pan de Yema', 4.50, 'Panaderia', 'Pan dulce de yema individual', 'CAF-PAN-004', '775120000042', 1.30, 'unidad'),
        ('Pan Integral', 5.00, 'Panaderia', 'Pan integral para acompanar desayunos', 'CAF-PAN-005', '775120000043', 1.50, 'unidad'),
        ('Baguette Personal', 6.50, 'Panaderia', 'Baguette pequena para sandwiches', 'CAF-PAN-006', '775120000044', 2.40, 'unidad'),
        ('Tostada Palta', 13.50, 'Panaderia', 'Tostada con palta y semillas', 'CAF-PAN-007', '775120000045', 5.20, 'plato'),
        ('Roll Canela', 9.50, 'Panaderia', 'Roll de canela con glaseado', 'CAF-PAN-008', '775120000046', 3.70, 'unidad'),
        ('Desayuno Americano', 24.00, 'Desayunos', 'Huevos, pan, cafe y jugo', 'CAF-DES-001', '775120000047', 11.20, 'plato'),
        ('Desayuno Criollo', 23.00, 'Desayunos', 'Tamizado criollo con cafe de la casa', 'CAF-DES-002', '775120000048', 10.40, 'plato'),
        ('Bowl Yogurt Granola', 15.00, 'Desayunos', 'Yogurt con granola y frutas', 'CAF-DES-003', '775120000049', 6.20, 'bowl'),
        ('Omelette Queso', 16.00, 'Desayunos', 'Omelette con queso y pan tostado', 'CAF-DES-004', '775120000050', 6.80, 'plato'),
        ('Tostadas Francesas', 17.00, 'Desayunos', 'Tostadas dulces con fruta y miel', 'CAF-DES-005', '775120000051', 7.00, 'plato'),
        ('Avena Frutas', 12.00, 'Desayunos', 'Avena caliente con frutas de estacion', 'CAF-DES-006', '775120000052', 4.20, 'bowl'),
        ('Ensalada Cesar', 18.00, 'Ensaladas', 'Lechuga, pollo, croutones y parmesano', 'CAF-ENS-001', '775120000053', 8.20, 'bowl'),
        ('Ensalada Quinua', 17.50, 'Ensaladas', 'Quinua, verduras y vinagreta', 'CAF-ENS-002', '775120000054', 7.80, 'bowl'),
        ('Ensalada Mediterranea', 18.50, 'Ensaladas', 'Vegetales, queso fresco y aceitunas', 'CAF-ENS-003', '775120000055', 8.10, 'bowl'),
        ('Bowl Pollo', 20.00, 'Ensaladas', 'Bowl con pollo, arroz y vegetales', 'CAF-ENS-004', '775120000056', 9.50, 'bowl'),
        ('Chips Papas', 6.00, 'Snacks', 'Papas chips porcion individual', 'CAF-SNK-001', '775120000057', 2.20, 'bolsa'),
        ('Mix Frutos Secos', 8.50, 'Snacks', 'Mix de frutos secos y pasas', 'CAF-SNK-002', '775120000058', 3.80, 'bolsa'),
        ('Barra Cereal', 5.50, 'Snacks', 'Barra de cereal energetica', 'CAF-SNK-003', '775120000059', 2.10, 'unidad'),
        ('Nachos Queso', 11.00, 'Snacks', 'Nachos con salsa de queso', 'CAF-SNK-004', '775120000060', 4.70, 'porcion')
) AS v(nombre, precio, categoria, descripcion, sku, codigo_barras, costo, unidad_venta)
JOIN categorias_producto c ON c.nombre = v.categoria
WHERE NOT EXISTS (
    SELECT 1 FROM productos p WHERE p.sku = v.sku OR p.codigo_barras = v.codigo_barras
);

UPDATE productos
SET costo = CAST(ROUND(CAST(precio * 0.38 AS NUMERIC), 2) AS DOUBLE PRECISION),
    margen_porcentaje = 62.00
WHERE costo = 0;

INSERT INTO inventario (
    nombre_insumo,
    codigo_insumo,
    categoria,
    ubicacion,
    lote,
    fecha_vencimiento,
    cantidad,
    unidad,
    stock_minimo,
    precio_unitario,
    proveedor_id,
    almacen_id,
    fecha_actualizacion
)
SELECT
    v.nombre_insumo,
    v.codigo_insumo,
    v.categoria,
    a.nombre,
    v.lote,
    v.fecha_vencimiento,
    v.cantidad,
    v.unidad,
    v.stock_minimo,
    v.precio_unitario,
    p.id,
    a.id,
    TIMESTAMP '2026-06-27 08:30:00'
FROM (
    VALUES
        ('Cafe organico premium', 'CAF-INS-CAFE-ORG', 'Cafe', 'L-CAF-2606-A', DATE '2026-12-31', 85, 'kg', 25, 38.00, 'ventas@andescoffee.pe', 'ALM-CENTRAL'),
        ('Cafe descafeinado', 'CAF-INS-CAFE-DES', 'Cafe', 'L-CAF-2606-B', DATE '2026-12-31', 36, 'kg', 12, 34.00, 'ventas@andescoffee.pe', 'ALM-CENTRAL'),
        ('Leche fresca', 'CAF-INS-LEC-FRE', 'Lacteos', 'L-LEC-2606-A', DATE '2026-07-20', 120, 'litros', 40, 4.80, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Leche deslactosada', 'CAF-INS-LEC-DES', 'Lacteos', 'L-LEC-2606-B', DATE '2026-07-20', 72, 'litros', 24, 5.20, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Crema batida', 'CAF-INS-CRE-BAT', 'Lacteos', 'L-CRE-2606-A', DATE '2026-08-15', 48, 'unid.', 16, 8.90, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Chocolate bitter', 'CAF-INS-CHO-BIT', 'Reposteria', 'L-CHO-2606-A', DATE '2027-01-30', 42, 'kg', 12, 22.00, 'pedidos@dulcenorte.pe', 'ALM-CENTRAL'),
        ('Harina pastelera', 'CAF-INS-HAR-PAS', 'Reposteria', 'L-HAR-2606-A', DATE '2027-02-28', 110, 'kg', 35, 5.80, 'pedidos@dulcenorte.pe', 'ALM-CENTRAL'),
        ('Mantequilla', 'CAF-INS-MAN-001', 'Reposteria', 'L-MAN-2606-A', DATE '2026-09-30', 65, 'kg', 20, 18.50, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Queso crema', 'CAF-INS-QCR-001', 'Reposteria', 'L-QCR-2606-A', DATE '2026-08-25', 58, 'kg', 18, 19.20, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Pulpa maracuya', 'CAF-INS-PUL-MAR', 'Frutas', 'L-PUL-2606-A', DATE '2026-10-10', 50, 'kg', 18, 11.50, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Naranja fresca', 'CAF-INS-NAR-001', 'Frutas', 'L-NAR-2606-A', DATE '2026-07-08', 180, 'kg', 50, 3.20, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Fresa congelada', 'CAF-INS-FRE-001', 'Frutas', 'L-FRE-2606-A', DATE '2026-11-12', 70, 'kg', 25, 9.80, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Pollo fileteado', 'CAF-INS-POL-001', 'Cocina', 'L-POL-2606-A', DATE '2026-07-18', 95, 'kg', 35, 12.50, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Pavo laminado', 'CAF-INS-PAV-001', 'Cocina', 'L-PAV-2606-A', DATE '2026-08-02', 42, 'kg', 18, 21.00, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Queso mozzarella', 'CAF-INS-QMO-001', 'Cocina', 'L-QMO-2606-A', DATE '2026-08-28', 60, 'kg', 20, 18.00, 'compras@distribuidoralima.pe', 'ALM-BARRA'),
        ('Pan molde integral', 'CAF-INS-PAN-INT', 'Panaderia', 'L-PAN-2606-A', DATE '2026-07-14', 150, 'unid.', 45, 1.60, 'pedidos@dulcenorte.pe', 'ALM-BARRA'),
        ('Croissant base', 'CAF-INS-CRO-001', 'Panaderia', 'L-CRO-2606-A', DATE '2026-07-10', 140, 'unid.', 40, 2.30, 'pedidos@dulcenorte.pe', 'ALM-BARRA'),
        ('Servilletas eco', 'CAF-INS-SER-ECO', 'Empaques', 'L-ECO-2606-A', DATE '2028-01-01', 2500, 'unid.', 600, 0.05, 'contacto@ecopack.pe', 'ALM-CENTRAL'),
        ('Tapas biodegradables', 'CAF-INS-TAP-BIO', 'Empaques', 'L-ECO-2606-B', DATE '2028-01-01', 1800, 'unid.', 500, 0.12, 'contacto@ecopack.pe', 'ALM-CENTRAL'),
        ('Bolsas delivery', 'CAF-INS-BOL-DEL', 'Empaques', 'L-ECO-2606-C', DATE '2028-01-01', 950, 'unid.', 250, 0.28, 'contacto@ecopack.pe', 'ALM-CENTRAL')
) AS v(nombre_insumo, codigo_insumo, categoria, lote, fecha_vencimiento, cantidad, unidad, stock_minimo, precio_unitario, proveedor_email, almacen_codigo)
JOIN proveedores p ON p.email = v.proveedor_email
JOIN almacenes a ON a.codigo = v.almacen_codigo
WHERE NOT EXISTS (
    SELECT 1 FROM inventario i WHERE i.codigo_insumo = v.codigo_insumo
);

INSERT INTO movimientos_inventario (
    inventario_id,
    tipo,
    cantidad,
    stock_anterior,
    stock_nuevo,
    costo_unitario,
    motivo,
    referencia,
    almacen_id,
    fecha_movimiento
)
SELECT
    i.id,
    'entrada',
    i.cantidad,
    0,
    i.cantidad,
    i.precio_unitario,
    'Ingreso inicial por ampliacion de catalogo',
    'V12-STOCK-INICIAL',
    i.almacen_id,
    TIMESTAMP '2026-06-27 08:45:00'
FROM inventario i
WHERE i.codigo_insumo LIKE 'CAF-INS-%'
  AND NOT EXISTS (
      SELECT 1
      FROM movimientos_inventario mi
      WHERE mi.inventario_id = i.id
        AND mi.referencia = 'V12-STOCK-INICIAL'
  );

UPDATE inventario
SET cantidad = cantidad + (
    SELECT v.delta
    FROM (
        VALUES
            ('Cafe especial', 64),
            ('Leche evaporada', 180),
            ('Azucar rubia', 140),
            ('Vasos biodegradables', 1200),
            ('Jarabe de vainilla', 48)
    ) AS v(nombre_insumo, delta)
    WHERE v.nombre_insumo = inventario.nombre_insumo
)
WHERE EXISTS (
    SELECT 1
    FROM (
        VALUES
            ('Cafe especial', 64),
            ('Leche evaporada', 180),
            ('Azucar rubia', 140),
            ('Vasos biodegradables', 1200),
            ('Jarabe de vainilla', 48)
    ) AS v(nombre_insumo, delta)
    WHERE v.nombre_insumo = inventario.nombre_insumo
)
AND NOT EXISTS (
    SELECT 1
    FROM movimientos_inventario mi
    WHERE mi.inventario_id = inventario.id
      AND mi.referencia = 'V12-REPOSICION'
);

INSERT INTO movimientos_inventario (
    inventario_id,
    tipo,
    cantidad,
    stock_anterior,
    stock_nuevo,
    costo_unitario,
    motivo,
    referencia,
    almacen_id,
    fecha_movimiento
)
SELECT
    i.id,
    'entrada',
    v.delta,
    i.cantidad - v.delta,
    i.cantidad,
    i.precio_unitario,
    'Reposicion por apertura de almacenes',
    'V12-REPOSICION',
    i.almacen_id,
    TIMESTAMP '2026-06-27 09:00:00'
FROM inventario i
JOIN (
    VALUES
        ('Cafe especial', 64),
        ('Leche evaporada', 180),
        ('Azucar rubia', 140),
        ('Vasos biodegradables', 1200),
        ('Jarabe de vainilla', 48)
) AS v(nombre_insumo, delta) ON v.nombre_insumo = i.nombre_insumo
WHERE NOT EXISTS (
    SELECT 1
    FROM movimientos_inventario mi
    WHERE mi.inventario_id = i.id
      AND mi.referencia = 'V12-REPOSICION'
);

INSERT INTO producto_receta (producto_id, inventario_id, cantidad_insumo, unidad, activo)
SELECT p.id, i.id, v.cantidad_insumo, v.unidad, TRUE
FROM (
    VALUES
        ('Cafe Americano', 'Cafe especial', 0.018, 'kg'),
        ('Cappuccino Clasico', 'Cafe especial', 0.018, 'kg'),
        ('Cappuccino Clasico', 'Leche evaporada', 0.250, 'latas'),
        ('Latte Vainilla', 'Cafe especial', 0.018, 'kg'),
        ('Latte Vainilla', 'Jarabe de vainilla', 0.050, 'botellas'),
        ('Espresso Simple', 'Cafe especial', 0.014, 'kg'),
        ('Espresso Doble', 'Cafe especial', 0.022, 'kg'),
        ('Latte Clasico', 'Cafe especial', 0.018, 'kg'),
        ('Latte Clasico', 'Leche fresca', 0.280, 'litros'),
        ('Mocha', 'Cafe especial', 0.018, 'kg'),
        ('Mocha', 'Chocolate bitter', 0.030, 'kg'),
        ('Cold Brew', 'Cafe organico premium', 0.030, 'kg'),
        ('Frappe Cafe', 'Cafe especial', 0.018, 'kg'),
        ('Frappe Mocha', 'Chocolate bitter', 0.025, 'kg'),
        ('Sandwich Pavo', 'Pavo laminado', 0.080, 'kg'),
        ('Panini Pollo', 'Pollo fileteado', 0.100, 'kg'),
        ('Croissant Mixto', 'Croissant base', 1.000, 'unid.'),
        ('Cheesecake Maracuya', 'Queso crema', 0.080, 'kg'),
        ('Cheesecake Maracuya', 'Pulpa maracuya', 0.040, 'kg')
) AS v(producto_nombre, insumo_nombre, cantidad_insumo, unidad)
JOIN productos p ON p.nombre = v.producto_nombre
JOIN inventario i ON i.nombre_insumo = v.insumo_nombre
WHERE NOT EXISTS (
    SELECT 1
    FROM producto_receta pr
    WHERE pr.producto_id = p.id
      AND pr.inventario_id = i.id
);
