-- V21: Sesiones de caja (apertura / cierre con monto inicial)
CREATE TABLE caja_sesiones (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          INTEGER NOT NULL,
    monto_inicial       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_ventas        NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_efectivo      NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cantidad_pedidos    INTEGER NOT NULL DEFAULT 0,
    estado              VARCHAR(20) NOT NULL DEFAULT 'abierta',
    fecha_apertura      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre        TIMESTAMP,
    monto_cierre        NUMERIC(12, 2),
    observaciones       VARCHAR(300),
    CONSTRAINT fk_caja_sesiones_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT ck_caja_monto_inicial CHECK (monto_inicial >= 0),
    CONSTRAINT ck_caja_total_ventas CHECK (total_ventas >= 0),
    CONSTRAINT ck_caja_total_efectivo CHECK (total_efectivo >= 0),
    CONSTRAINT ck_caja_estado CHECK (estado IN ('abierta', 'cerrada'))
);

CREATE INDEX idx_caja_sesiones_usuario ON caja_sesiones (usuario_id);
CREATE INDEX idx_caja_sesiones_estado ON caja_sesiones (estado);

CREATE UNIQUE INDEX ux_caja_usuario_abierta
    ON caja_sesiones (usuario_id)
    WHERE estado = 'abierta';

COMMENT ON TABLE caja_sesiones IS 'Turnos de caja: apertura con fondo inicial y registro de ventas del turno';
